### ISSUE TITLE
3rd level teleports players on top of mountains where kills players

### ISSUE THREAD

**Issue by Miamlya** [mim1q/MineCells#106]
Sometimes, the three-level dimension teleports players to the tops of mountains.

**Comment by mim1q** [comment]
Likely a duplicate of [the previous issue](https://github.com/mim1q/MineCells/issues/105)

**Comment by Miamlya** [comment]
![image](https://github.com/mim1q/MineCells/assets/145864992/61a8afed-9f31-4a5f-8c26-11cd685a6863)

**Comment by Miamlya** [comment]
Maybe it would be helpful; this location damages survival players
