### ISSUE TITLE
Outdated structures cause DFU to process every time they are loaded

### ISSUE THREAD

**Issue by Linguardium** [mim1q/MineCells#107]
V 1.7.2
AOF7 modpack 2.0.2

You have outdated structure files in your mod. This causes minecraft to try to update them every time they are loaded, leading to extra memory and cpu usage during worldgen. Please update your structures to match the mc version you are releasing for.

This should be as easy as loading them into game and re-saving them or using a mod to load them into a StructureTemplate and writing them back out to nbt.

**Comment by mim1q** [comment]
Thank you for the heads up! I made a custom little mod to resave all the structures, hopefully that does the job. It'll be released with the next major update
 [9493edc](https://github.com/mim1q/MineCells/commit/9493edc27a61e9b573f375a1b9f6702b86fd811d)
