### ISSUE TITLE
Breaking Doorways before entering dimensions softlocks Minecells progression

### ISSUE THREAD

**Issue by redrafa** [mim1q/MineCells#108]
First engagement with the mod without looking anywhere I instantly moved the first portal I found to a custom room in my base, upon going into the first dimension I basically did the same with the other 2 portals, upon placing them in Overworld both gates are locked which weren't when I broke them, I did not try to enter them in the Prisioners Quarters, tried to force TP myself into both dimensions and back to overworld to see if it changed anything but nothing was changed.

**Comment by redrafa** [comment]
Modpack author didn't update the mod but indicated to relay the issue with the mod author, upon digging myself this issue as of 1.7.2 is fixed (mod was 1.6.2)

**Comment by mim1q** [comment]
Yes, these portals inside Mine Cells dimensions were never meant to be broken - it was an accidental oversight, which is now fixed 😅
