### ISSUE TITLE
BUG: teleported players into the mountains in the Ramparts

### ISSUE THREAD

**Issue by MrShellad** [mim1q/MineCells#109]
teleported players into the mountains in the Ramparts
 Versions：minecells-1.20.1-1.7.3
latest version still does not fix this bug.
This BUG will also appear in a single MOD.

**Comment by PinkD3vil** [comment]
yep found out this bug the hard way

**Comment by mim1q** [comment]
The temporary workaround for 1.7.3 is to disable the Ramparts fall protection mechanic in the `minecells-common.json5` config. 

I'll see why else this weird issue could be happening in the new release, but I'll most likely just redo the whole mechanic to be a bit more predictable.

**Comment by mim1q** [comment]
The mechanic will now always telport you to the start of the biome, so this mountain teleport glitch should no longer happen, and if it does - jumping down should put you in the correct spot 😅
