### ISSUE TITLE
Mine Cells 1.8.x crashes with Sinytra Connector due to @ModifyExpressionValue mixins failing

### ISSUE THREAD

**Issue by GauntAndreX8** [mim1q/MineCells#111]
New version of mod causes crash on start
when going back to 1.7.4
it doesn't crash
[crash-2024-05-12_15.35.11-client.txt](https://github.com/mim1q/MineCells/files/15287860/crash-2024-05-12_15.35.11-client.txt)

**Comment by mim1q** [comment]
Ahh, I know a similar crash happens when you use older versions of Fabric Loader, but I didn't even think to check Connector

Do you have the latest version of Sinytra Connector? If not, try to update that. I'll check this bug out tomorrow and see if there's any other apparent fix

**Comment by mim1q** [comment]
Most likely a Connector incompatibility with MixinExtras, unless I'm missing something here. 
There's an issue open in Connector's repo: https://github.com/Sinytra/Connector/issues/1085

**Comment by GauntAndreX8** [comment]
im using the latest Connector, still causes crash

**Comment by mim1q** [comment]
Fixed with https://github.com/Sinytra/Connector/issues/1085
