### ISSUE TITLE
[1.19.2] Spawner Runes possibly causing the server to hang @ Medieval MC [FABRIC] - MMC1

### ISSUE THREAD

**Issue by KuryKat** [mim1q/MineCells#119]
Related to #117, similar symptoms to AllTheMods/ATM-8#507, EnigmaticaModpacks/Enigmatica9#299 and FTBTeam/FTB-Modpack-Issues#2531

---

Hey there! My friend asked me to help them manage/host their server, and came to me saying that ALL players had been disconnected with just `"Timed Out"` and were not being able to join the server again (with the same issue) so I started investigating what could be the cause...

2 days ago, before the issue happened, I so happened to make a [spark profiler](https://spark.lucko.me/Jr3Uy1N1wF) because the server was running ``400 ticks behind``, and saw that there was a lot of usage on entity ticking

![image](https://github.com/mim1q/MineCells/assets/57152799/34883131-c413-449b-a883-0c3ef6ab07b8)

At that time we found out that ``neruina`` could be the cause, so we removed it (just from the server) following the advice of a friend that said to know that it is known to cause those issues sometimes to see if that would help

It indeed helped, server went from running ``400 ticks behind`` to running ``100 ticks behind``, and I made a [second profiler](https://spark.lucko.me/3DlpJSpIlj) to see if things were better, and they seemed a *little* better, I still asked my friends to keep their eyes opened for any lag spikes and let me know.

Then yesterday I saw there was a LOT of entities called "Spawner Rune" when executing a `/say @e` out of curiosity to see the entities that were alive
> [!NOTE]
> I only have access to the server's terminal, so that was the only way I had to see all alive entities

![image](https://github.com/mim1q/MineCells/assets/57152799/871aebeb-57a1-4f04-b288-92936d61ef3c)

I asked my friend if they knew what those entities were, and they told me nobody knew what or where they were, and so I kept my eye open.

Hours later they told me about the issue of timing out, and when seeing the logs I saw a spam of

```
[23:45:48] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[23:46:48] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[23:47:48] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[23:48:48] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[23:49:48] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[23:50:48] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[23:51:48] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[23:52:48] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[23:53:48] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[23:54:48] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[23:55:48] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[23:56:48] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[23:57:48] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[23:58:48] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[23:59:48] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
```

which implies that the server was hanging for a **while**!

I suspect that it could be somehow related to how Spawner Runes works, are they forcing chunks to be perma loaded? or something like that? In any case, a spam of said entity doesn't really seem like a good thing, and I highly suspect it was the cause of the server hanging due to too many chunks being loaded, causing a hardware overload.

After a server restart they were able to join back, but the issue might happen again soon.

> [!NOTE]
> I thought of using something like Crash Utilities to debug the issue further, but sadly it isn't available to Fabric, do you know any mod that I could use to investigate the issue further?

**Comment by KuryKat** [comment]
Sorry, I confused things a little bit, edited the description to better explain the whole situation

**Comment by mim1q** [comment]
The pack uses an outdated version of Mine Cells, actually! I can see you have 1.5.3, when 1.5.8 is available, and has fixed many of the issues Spawner Runes had. 
(They are now block entities by default, and only turn into "true" entities when you place a block on top of them, which has in my experience been a huge performance upgrade)

I'm actually not sure if this is related to the spawner runes, they don't seem to be hogging up too many resources by themselves in this scenario, but it's still worth a try!

If you do update, you'll likely need to reset all Mine Cells dimensions for the Spawner Runes to regenerate correctly. Please let me know if the 1.5.8 version fixes the issue.

Also: I'm don't really know any mods that could help, sorry 😅

**Comment by KuryKat** [comment]
Ohhh thanks for the reply and I'm sorry for the late answer, I will try what you've recommended, it makes sense!

Actually I discovered that spark was running a background profiler so I uploaded it and [here are the results](https://spark.lucko.me/Pm56EK3qrl)

So it seems that there *really* was way too many Spawner Runes, out of 2077 entities in total, 1155 were them!!

![image](https://github.com/mim1q/MineCells/assets/57152799/49a718f1-0190-494b-bdbd-340bd3a1122d)

I will try updating the mod to see if that fixes the issue!

~~Are there any steps I need to take before updating it or it's a safe update to make without need of some migration?~~
~~Edit: Just noticed your point about needing to reset the dimension, could you tell me the dimensions' ids?~~
Edit²: Nevermind I figured it out, for a second I forgot that modded dimensions have a "dimensions" folder where it's the MOD_ID XD

**Comment by KuryKat** [comment]
Update: The server seems to be running a lot better now with 1.5.8

[This](https://spark.lucko.me/Uk1VGQoR39) is a profiler made in the 2 hours right after updating the server, when there was more players online

![image](https://github.com/mim1q/MineCells/assets/57152799/3f7897ea-4261-4a01-bea1-a6382d9f69cb)

[This](https://spark.lucko.me/HHKakQjbzA) is a profiler made in the last 6 hours, when there isn't many players online

![image](https://github.com/mim1q/MineCells/assets/57152799/44802c53-dce9-470f-8e71-5649433207eb)

Both them show a huge improvement, back on 1.5.3, even with no players online the server would be on low TPS all the time because of the huge amount of entities that were spawned

Since 1.5.8 seems to fix this issue, I will forward a request for LPS to update their pack including 1.5.8, this is a needed fix.

I will leave to you if we should close this issue or not yet! ^^

**Comment by mim1q** [comment]
I'm part of LPS, actually. I'll mention this issue directly :sweat_smile: 

Thanks for all the reports! I'll close this now, if the issue reappears for any reason feel free to comment again!

**Comment by Suriossas** [comment]
Good afternoon, had a similar problem, at first the error of building world statistics, and after the message that it does not keep up with a delay of 20000 or more milliseconds. After checking what it can be, I came to the conclusion that in a particular chunk, there is an object “Excavator” in the modepack Valhelsia 6, which when loaded just causes a huge delay in ticks. After reading this problem, I can assume that some entities or rather blocks of ore at this point fail. I don't know what can be done about it
