### ISSUE TITLE
Accidentally deleted promenade portal and now cannot figure how to get it back.

### ISSUE THREAD

**Issue by Euphonit** [mim1q/MineCells#120]
I was in the prison dimension and found the promenade portal. Earlier I had broken the block behind the prison portal and it dropped and I moved it into my base for easier access. I wanted to do the same thing with the promenade portal but I had not generated the dimension yet and went into creative to break the unbreakable blocks behind hoping it would drop the portal. Then in creative mode, I misclicked and broke the portal itself. I tried to figure out how to get in back by using /place, but nothing worked. I am opening this issue to ask how to regenerate the portal and place it back in my world.

**Comment by Euphonit** [comment]
I figured out how to spawn it back it by just finding a different portal

**Comment by Euphonit** [comment]
I figured out how to spawn it back it by just finding a different portal

**Comment by mim1q** [comment]
Hah, yeah - the blocks are unbreakable specifically so this wouldn't happen in survival 😁 

You can still get a Promenade portal in your base, though! What you need to do is: 
- place a Prisoners' Quarters portal
- make sure you have visited the Promenade *through the placed portal*
- then use a Promenade Dimensional Rune on the doorway, and it should turn into a Promenade one!
