### ISSUE TITLE
"gimm1q" on modmenu

### ISSUE THREAD

**Issue by lalalokat** [mim1q/MineCells#122]
hey! i don`t know is it issue or not, but I recently downloaded the Mine Cells - Dead Cells Mod with the oωo (owo-lib), and when I`am using them, the "gimm1q" section is appearing on modmenu, with no description, no photo and etc. is ts supposed to be like that? 

![Снимок экрана 2024-06-09 233031](https://github.com/mim1q/MineCells/assets/172204766/6c58085c-8761-4654-b11a-cdd9a2ec1aae)

**Comment by mim1q** [comment]
Yes, Gimm1q is my library that I use in a few of my mods to make things a bit easier for me 😅 
It's open source and available here: https://github.com/mim1q/gimm1q
Thanks for bringing this to my attention, I will update it to have a short description so people know it's supposed to be there!
