### ISSUE TITLE
[Suggestion] Support for chains from other mods 

### ISSUE THREAD

**Issue by kingkuys2123** [mim1q/MineCells#19]
A chains block tag maybe for Hanging Skeleton/Corpses to add support for other mods' chains

**Comment by mim1q** [comment]
That's probably a good idea. Is there a common tag for chains or will I have to create a new one?

Also, the way it works right now is that it checks if some block is a subtype of Chain, so if someone codes their custom chain that way, it'll work right now.

**Comment by kingkuys2123** [comment]
Yeah, you would probably need to create a new one. And I just tried hanging the corpses earlier with modded chains, and all but one of them worked. So perhaps you don't even need to create the block tag at all. 🙂
![2023-01-02_12 28 06](https://user-images.githubusercontent.com/114457180/210195738-92f29f09-dc30-431a-be0b-7690460cbafc.png)

But if you do, I have a chains block tag in my mod-pack and reordered it for you, if you like
https://pastebin.com/gxbSvuCr

**Comment by mim1q** [comment]
Can you please modify the json to only include chains that are similar to vanilla's chains? Like the first two in the screenshot, and exclude the "bigger" ones. I'd use that for the elevator's chains :)

**Comment by kingkuys2123** [comment]
Here you go! :) 

https://pastebin.com/rPJz6jr6

**Comment by mim1q** [comment]
Thank you! Ah, I could have waited a bit longer with the latest update, just released it an hour ago. Guess I'll include this in the next release, thank you so much! :smiley:

**Comment by mim1q** [comment]
Included an `elevator_chains` tag in f098b7481c7834c7feb59fae59c20cbca65e56f1! :)
