### ISSUE TITLE
Cell Forge missing recipe

### ISSUE THREAD

**Issue by itsdinkd** [mim1q/MineCells#20]
As title says, cell forge has no recipe in the latest 1.19.2 version.

**Comment by itsdinkd** [comment]
looking at the data file you have the type set to ` "type": "minecells:cell_forge_recipe",` 

So my assumption is Minecells is not compatible with REI hence me not seeing recipe,. and also, how is one supposed to craft a cell forge in a cell forge?

**Comment by mim1q** [comment]
Hi, the Cell Forge is not available in survival yet. Sorry for not making it clear 😅 

I still have to sort some things out before making it usable, like REI compatibility. And I have to figure out if the Cell Forge is actually the best approach, or if I should do something different in its place.

I can change the name to "Cell Forge (creative only)" until it's ready / replaced

**Comment by itsdinkd** [comment]
Ah this makes sense. i imagine "cells" are also not yet ready? not seeing any at all

**Comment by mim1q** [comment]
You can turn on the `minecells.mobsDropCells` gamerule to make them drop! But for now they're disabled, because without the cell forge they have no use

**Comment by mim1q** [comment]
Recent version adds a completely reimagined and fully fleshed out version of the Cell Crafter!
