### ISSUE TITLE
Crash of unknown nature (NPE)

### ISSUE THREAD

**Issue by importnil** [mim1q/MineCells#21]
Hi,

Was playing with a friend, we both have experienced a client crash (and it's the same stack trace for both of us) under unknown circumstances. We were not even close to the portal, it seems that it crashes in the event of a chunk being loaded but not sure because after logging back into the server and loading the chunks with portal everything was fine. And then again after a few minutes of playing around, the same crash. Please see attached report.

[crash-2023-01-09_23.02.02-client.txt](https://github.com/mim1q/MineCells/files/10377277/crash-2023-01-09_23.02.02-client.txt)

**Comment by importnil** [comment]
Posting another crash report (not the same one) as it seems it's related to this one.
Happened while teleporting far away from one portal to another.

[crash-2023-01-09_23.36.20-client.txt](https://github.com/mim1q/MineCells/files/10377431/crash-2023-01-09_23.36.20-client.txt)

**Comment by mim1q** [comment]
Hello, thank you for reporting!
It seems that a variable isn't initialized correctly, that's weird. Never happened before, so that might be the fault of some mod combination you're using.
Nonetheless it should be a pretty easy fix on my end, I'll just add a default value that gets used before the correct one is calculated

**Comment by importnil** [comment]
Does it make sense to initialize all possible critical nulls?
I can see a new crash with another variable :P

P.S. Sorry if I'm being too ignorant, completely not into Java or Fabric modding.

[crash-2023-01-10_00.03.43-client.txt](https://github.com/mim1q/MineCells/files/10377542/crash-2023-01-10_00.03.43-client.txt)

**Comment by mim1q** [comment]
Yeah that would be one way to solve it, but I think I'll just change the approach a bit

**Comment by mim1q** [comment]
Possibly fixed in 1.3.4! Are you able to verify that?

**Comment by mim1q** [comment]
1.3.4 introduced defaulted values for the portal's data. Other players have confirmed this as fixed

**Comment by importnil** [comment]
Yes, looks good to me. Thank you :)
