### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by ereese99** [mim1q/MineCells#23]
Is it possible to make this mod compatible with 1.19.3? Thanks

**Comment by mim1q** [comment]
Hi! Unfortunately, 1.19.3 had some pretty big changes that mean I'd have to update quite a bit of the mod's code. Mine Cells is present in a lot of 1.19.2 modpacks, so updating to 1.19.3 would make it difficult for me to release new content for these modpacks to use. For now, Mine Cells will remain on 1.19.2, I'll probably only update when 1.20.x becomes a standard for modpacks. Sorry!
