### ISSUE TITLE
[Suggestion] Disable Spawn Setting [1.19.2]

### ISSUE THREAD

**Issue by itsdinkd** [mim1q/MineCells#24]
disable being allowed to set spawn in prison dimension

**Comment by mim1q** [comment]
Hey - beds should explode when used there. I left respawn anchors on in case someone really needed to set their spawn. What's the reason of this suggestion, is there some bug?

**Comment by mim1q** [comment]
Disabled spawn setting in Mine Cells dimensions, both with beds and respawn anchors in the latest update.
