### ISSUE TITLE
Too many portal spawns

### ISSUE THREAD

**Issue by IMadeThisJustToPostThis** [mim1q/MineCells#26]
It feels like the portal spawns are way too common, because I've seen these things about 10 different times in my world already and I just started the world a few days ago. I would appreciate a solution to this, either a more rare spawn or removing the spawns altogether and giving the ability to build the portal. Another potential solution is moving it from being a surface structure to being an underground structure

(also if this get's implemented pls make a 1.19.2 version as well as a 1.19.3 version with this update 🥺🥺🥺🥺)

**Comment by IMadeThisJustToPostThis** [comment]
Also, this is besides the point, but I think it would be neat if there were some sort of ritual required to turn on a portal as opposed to just having obtained a diamond, but that's more of a feature suggestion and less of a quality of life fix

**Comment by mim1q** [comment]
Hey, I'll tune down the spawn rate, it really is way too common 😄 
I'd really like to make it an underground structure and/or make some ritual for it, but for now I'm focused on other things.
Also, a 1.19.3 version is probably not coming. A lot of the internal code changed so I'd have to have two separate branches for 1.19.3 and 1.19.2, which I don't really have that much time for, sorry

**Comment by mim1q** [comment]
Made the portals more rare with the latest 1.3.4 version! Closing this - as said above, I might remake the portals' mechanics in the future, and a 1.19.3 version is not planned

**Comment by IMadeThisJustToPostThis** [comment]
> Hey, I'll tune down the spawn rate, it really is way too common 😄 I'd really like to make it an underground structure and/or make some ritual for it, but for now I'm focused on other things. Also, a 1.19.3 version is probably not coming. A lot of the internal code changed so I'd have to have two separate branches for 1.19.3 and 1.19.2, which I don't really have that much time for, sorry

i'm completely okay with that, I was moreso concerned that the update would be for 1.19.3 only as i play on 1.19.2 lol. Thanks for the super fast update and appreciate the work done on the mod!!
