### ISSUE TITLE
Incompatible with Immersive Portals

### ISSUE THREAD

**Issue by Zarepheth** [mim1q/MineCells#30]
I'm not asking for the Mine Cells portals to to operate like Immersive Portal's redo of Nether and End Portals, though that would be great. However, I would appreciate the two mods being sufficiently compatible that having both present would not crash the game.

[latest.log](https://github.com/mim1q/MineCells/files/10832561/latest.log)

**Comment by mim1q** [comment]
74a5b4f seems to have fixed it! 
A beta will be released around Monday. Please let me know if the issue stops occurring after the update!

**Comment by mim1q** [comment]
[The 1.4.0 beta](https://www.curseforge.com/minecraft/mc-mods/minecells/files/4412616) is out early, in case you want to verify it :)

**Comment by Zarepheth** [comment]
Thank you!
That seems to fix things - both in my Medieval MC based Curse Forge profile and my test profile.

**Comment by mim1q** [comment]
Glad to hear that! Closing, consider marking [the other issue](https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1290) as closed, too :)
