### ISSUE TITLE
minecells/rpgdifficulty incompatibility

### ISSUE THREAD

**Issue by soupcantrolling** [mim1q/MineCells#32]
https://mclo.gs/6PYi4md

1.19.2 fabric,
entered a mine cells portal thing and shortly after the game crashed. the report shows its due to both minecells and the rpg difficulty mod, im guessing it's trying to make one of the rune spawn mobs stronger and it can't find how.

im reporting this on both mods' issue pages

**Comment by mim1q** [comment]
Does it work with version 1.3.5 of RpgDifficulty?

**Comment by mim1q** [comment]
Fixed on RpgDifficulty's end!
