### ISSUE TITLE
Any way to completely remove a Mine Cells portal?

### ISSUE THREAD

**Issue by James103** [mim1q/MineCells#33]
Is there any way I could possibly **completely** remove a Mine Cells portal in the Overworld (as in not just the blocks but the portal itself)? It is conflicting with one of my future builds in one of my survival worlds that use this mod.

More specifically, if I use `/fill ... air` (which I'm willing to do) to remove the portal outline, would that also remove/close the portal itself? If not, what else do I have to do to get rid of the portal?

I checked for NBT data inside each of the twelve portal structure blocks with `/data get block` and none of them had any.

Originally found in Mine Cells version 1.3.5 which is part of All of Fabric 6 version 1.5.0.

**Comment by mim1q** [comment]
The easiest way to remove the portal would be to just go into creative and destroy one of the blocks manually. The whole portal should be removed that way.

If you have to use commands, a single `/setblock` won't do the trick. But using `/fill` or something like that to replace the entire structure with air should work. One of the bottom invisible blocks inside the portal is a `minecells:kingdom_portal_core`, and that is what's responsible for the portal itself.

Other than that, I'm still thinking of a good way to make them either less obstructive or just movable in survival :)

**Comment by mim1q** [comment]
You can now break, place and craft your own portals, starting with Mine Cells 1.5.0 :)
