### ISSUE TITLE
Comparators no longer update until they are forcefully updated

### ISSUE THREAD

**Issue by jpenilla** [mim1q/MineCells#36]
Something between 1.3.5 and 1.4.1 broke comparators.
Might be this commit? https://github.com/mim1q/MineCells/commit/390d2198481741d2dc9ad4cc9c2c3ff978a7d1f3

See https://github.com/TeamAOF/All-of-Fabric-6/issues/202

**Comment by mim1q** [comment]
Fixed in main branch with commit 046dd33
