### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Firestrike1** [mim1q/MineCells#4]
[latest.log](https://github.com/mim1q/MineCells/files/8942620/latest.log)

I think this thread covers the issue: https://www.reddit.com/r/fabricmc/comments/l1ffww/issue_starting_own_mod_on_the_server/

**Comment by mim1q** [comment]
Thank you for reporting!
Fixed in https://github.com/mim1q/MineCells/commit/4e1dd1fdb893001cf32bd52738ae1935ff0c8747
[Version 0.3.0 with the bug fixed and new content added is now out on Modrinth.](https://modrinth.com/mod/minecells/version/0.3.0)
