### ISSUE TITLE
Cannot find The Conjunctivius

### ISSUE THREAD

**Issue by Jonxthxn-A** [mim1q/MineCells#41]
Have looked and tried everything to find the boss, and nothing is working. We have acquired Vine Rune from the dungeons yet we cannot find the boss, there is no information available on finding the boss

**Comment by mim1q** [comment]
Hey, sorry for the lack of info - the mod is changing every update, I'll try to make a guide for the next one. When you have the rune, go back to the Prisoners' Quarters. On the top floor there's a room with a plant that you have to activate with the Vine Rune :)

**Comment by mim1q** [comment]
All necessary info is now available [on the wiki ](https://mim1q.dev/minecells/progression-guide/)

**Comment by Simplebenja** [comment]
I have this same issue in 1.21.1, I searched every Prision level and nothing

Mod list:
minecells-2.0.3
fabric-api-0.116.7+1.21.1
owo-lib-0.12.15.4+1.21
cardinal-components-api-6.1.2

[Log](https://github.com/user-attachments/files/23109435/Runic.vine.Boss.log)

[Video](https://youtu.be/GEIWoGmEpC8)
