### ISSUE TITLE
Crash with dotless i

### ISSUE THREAD

**Issue by Juuxel** [mim1q/MineCells#45]
See FabricMC/fabric#3098. Mine Cells uses `toLowerCase()` without specifying the locale for a block state property enum:

https://github.com/mim1q/MineCells/blob/c38f478a0956992754079ac116a39d9f92e87e1f/src/main/java/com/github/mim1q/minecells/block/WoodenBoardBlock.java#L89

When `MIDDLE` is used as a property value in a Turkish-locale environment, it gets turned into `mıddle`. The game then crashes with an exception from MC's property validation code.

**Comment by mim1q** [comment]
That's what I get for trying to save a few lines of code 😅 I'll fix that for the next release, will link the commit later today!

**Comment by mim1q** [comment]
Should be fixed with this commit: b3b5b5d
