### ISSUE TITLE
Can't figure out how to install an elevator

### ISSUE THREAD

**Issue by unhack12** [mim1q/MineCells#46]
i know i'm dumb but could someone explain to me how to install on a chain elevator

**Comment by mim1q** [comment]
I made a video tutorial on YouTube specifically for that :smile: 
Here's the link, let me know if that resolves your issue:
https://youtu.be/QW_D-kVoD4E

**Comment by unhack12** [comment]
yes it solved my problem. Thank you so much for your quick response and solution!
