### ISSUE TITLE
My mod pack doesn't want to launch with mine cells in it

### ISSUE THREAD

**Issue by kart180** [mim1q/MineCells#49]
I put the error code here as well 

[crash-2023-07-21_17.36.02-client.txt](https://github.com/mim1q/MineCells/files/12134999/crash-2023-07-21_17.36.02-client.txt)

So the game just won't load all together as I put in the title. If u need to see the mods in the mod pack or anything else, I'll send it here if i can

**Comment by kart180** [comment]
Also, here is what it said 
(java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'minecells'!)

**Comment by mim1q** [comment]
Try updating owo-lib to 0.9.3

**Comment by kart180** [comment]
Oh sry I didn't see. Was asleep. And tnx cause it worked :) I appreciate it
