### ISSUE TITLE
failed to load world (SP)

### ISSUE THREAD

**Issue by AmonRay** [mim1q/MineCells#50]
https://pastebin.com/aix5Xyy7

**Comment by mim1q** [comment]
What modpack is this? It probably changes the spawn rates of the old portal structures, which don't exist anymore. So that config has to be changed. It might be a datapack added to the world or some other structure configuration option.

**Comment by AmonRay** [comment]
true

removed kubejs script

`{
  "type": "minecraft:jigsaw",
  "biomes": "#minecells:valid_portal_biomes",
  "step": "surface_structures",
  "spawn_overrides": {},
  "terrain_adaptation": "beard_thin",
  "start_pool": "minecells:portal",
  "size": 1,
  "start_height": {
    "absolute": 0
  },
  "project_start_to_heightmap": "WORLD_SURFACE_WG",
  "max_distance_from_center": 5,
  "use_expansion_hack": false
}`

thanks
