### ISSUE TITLE
Portals won't spawn (even already explored ones) and in it's place is a "BREAK ME"

### ISSUE THREAD

**Issue by kart180** [mim1q/MineCells#51]
Idk what's goin on and this is after I fixed the problem with my mod pack not being able to load

**Comment by mim1q** [comment]
Portals have been completely changed! If you break the *BREAK ME* block, (as suggested 😁) you should get the new one to place wherever you want.

**Comment by kart180** [comment]
How would I place it? Like any other block?

**Comment by kart180** [comment]
I tried to place it, but it doesn't work like a regular block

**Comment by kart180** [comment]
It also tells me that I haven't explored enough of smtn and shows me cords that don't have anything (at least in the overworld)

**Comment by mim1q** [comment]
Place it against a big wall 😅 
I'll try to update the wiki soon to explain that better

**Comment by kart180** [comment]
I'll try that

**Comment by kart180** [comment]
Sry. Fell asleep again. It works tho. Tnx again :)
