### ISSUE TITLE
Updated All The Fabric 6 Modpack and Server won't launch

### ISSUE THREAD

**Issue by FaithfulRyan** [mim1q/MineCells#52]
I recently updated the ATF6 modpack which went from Mine Cells version 4.3 to version 5.3 and I had to manually install the new mod into both my server files and client files. After doing so I followed the update instructions and reset my world's dimension for dead cells by deleting the folder. After doing so my server, and client when attempting to generate a new world, crash with this [log](https://pastebin.com/8HvZd5zR). Any assistance would be greatly appreciated!

**Comment by FaithfulRyan** [comment]
Hey, just wanted to say I looked through some of the solved issues and discovered #50 which had the solution to my problem. I apologize for not seeing this before making a post about it. Hope this helps anyone else who may be having this issue! For those too lazy to read, you need to go into *your server folder or instance*/Kubejs/data/minecells/structures and remove the "portal.json" file from this folder on both your client and server files.

**Comment by mim1q** [comment]
No need to apologise - glad you figured the crash out yourself 😁
