### ISSUE TITLE
What is Beam Placer

### ISSUE THREAD

**Issue by seaseii** [mim1q/MineCells#54]
I am a Chinese translator and I have not found the Beam Placer.
Can you tell me where it appears or send me a screenshot?Thx: )
    "block.minecells.beam_placer": "Beam Placer"

**Comment by mim1q** [comment]
Hey, the beam placer is a technical block that shouldn't ever be accessible to a normal player, so it doesn't need a translation 😅

 It's used to extend the "legs" of structures in the Promenade down so they always touch the ground. Disappears immediately after it does that, right after the structure first generates.

**Comment by seaseii** [comment]
thx,I like this Mod.Because It reminds me of Dead Cells. I really like Dead Cells and hope Mine Cells becoming better and better: )
