### ISSUE TITLE
[BUG] texture not loading

### ISSUE THREAD

**Issue by Kiryonn** [mim1q/MineCells#55]
| Minecraft Version | Loader | Loader Version | Mod_version |
|---|---|---|---|
| 1.19.2 | Fabric | 0.14.21 | 1.5.3 |

in the logs i've seen an error where "minecells:textures/block/putrid_log_side.png" don't load

**Comment by mim1q** [comment]
The texture is used in the unused "Cell forge" block. So it isn't an issue, because the block shouldn't even be seen in regular gameplay, yet. I'll keep this issue up until the block actually gets added (and by that time the model will surely be fixed 😁)
