### ISSUE TITLE
Some areas in prison spawn encased in hardstone

### ISSUE THREAD

**Issue by jack9761** [mim1q/MineCells#58]
I noticed on the minimap that there were some things in the void. I entered spectator mode and saw there was generation that was unreachable because it was out of bounds. 
Modpack: Prominence 2 Fabric
Seed: 7195293445123065821
Coords -5104 8 2024
![2023-09-09_22 25 46](https://github.com/mim1q/MineCells/assets/86904468/bdc0f78d-e474-4e08-b2d8-0d1a2026b13f)
![2023-09-09_22 25 54](https://github.com/mim1q/MineCells/assets/86904468/fe31d178-fdea-4fd9-ba2a-7b28216df796)

**Comment by mim1q** [comment]
I can't do anything about this until Thursday unfortunately, but I believe this doesn't happen when only Mine Cells is present. Might be some mod modifying structure placement? Seems like the air doesn't actually get placed, hm.

**Comment by mim1q** [comment]
Sorry for closing the issue, that was a missclick 😅

**Comment by linaraincalzando** [comment]
Had same issue, I do have sparser structures installed.

**Comment by mim1q** [comment]
@linaraincalzando in your case, I can see Sparser Structures does have a config option to blacklist some mods. You should do that with minecells, because that mod makes the dungeons pretty much not spawn most of the time, I believe

**Comment by linaraincalzando** [comment]
Oh wonderful! I didnt know if Prominence 2 has sparser structures or not so I thought I would bring it up, I didn't even contemplate there was a config for it. I was just going to yeet the mod to keep minecells. You made my monday, thank you!
