### ISSUE TITLE
Is there a 1.19 branch?

### ISSUE THREAD

**Issue by Ricenami** [mim1q/MineCells#61]
I'm not a modpack developer, but I have basic knowledge to edit values in code, I want to change the damage of the weapons and the hp of entities, but when I tried building the .jar file, I realized that it was for 1.20.

**Comment by mim1q** [comment]
Yes - it was named `main`. I changed it to `1.19.2` now to avoid confusion 👍 
You may be better off changing the item damage using scripting tools such as Kube JS 🤔(not sure how to change the entity HP and stuff though)

**Comment by Ricenami** [comment]
Thank you for your help!
