### ISSUE TITLE
[Suggestion] Make big chains function like cave vines plant

### ISSUE THREAD

**Issue by Rad586** [mim1q/MineCells#62]
It's frustrating to look up and find the hole up. Also, in dead cells, player can pass through chains. 
Making big chains function like cave vines plant(passable and climbable) would be cool.

**Comment by mim1q** [comment]
Oh, this is a pretty great suggestion! Maybe I should make it so the vertical ones are passable and horizontal ones aren't?

**Comment by mim1q** [comment]
Implemented - big chains will behave like this from the next update onwards 😁
