### ISSUE TITLE
Release 1.5.3 Portals just lead to an empty dimension

### ISSUE THREAD

**Issue by Zarvera** [mim1q/MineCells#64]
Well, as the title says. No sure what to add, as it doesn't crash or anything. I've tried several "Prisoners Quarters" dimensions and it's all just empty dimension with smooth hardblock floor at y64

**Comment by mim1q** [comment]
Can you provide a mod list? If you're using a mod like Sparse Structures, you might have to delete or configure it because it messes with the placement system

**Comment by Zarvera** [comment]
I don't, but considering there're several mods that behave incorrectly i just had a thought that it might be some specific mod disrupting other mods including yours. I strongly feel this issue is a mistake because most probably it's not your fault in any way at all. Fabric has this quirk about itself.
Anyway, modlist is:
Advanced Tooltips
Paradise Lost
Amecs
Animatica
AppleSkin
Architect's Palette [Fabric]
Architectury API
AttributeFix
Aylyth
AzureLib
BCLib
Beacon Overhaul
Beneath the Wetlands
Better Combat
Better Jukebox
BetterEnd
Bits And Chisels
Bookshelf
Bosses of Mass Destruction
Botarium
Brainier Bees
Cardinal Components API
Catwalks Inc.
ChickensShed
ChoiceTheorem's Overhauled Village
Chunk Loaders
Cloth Config API
Collective
Concurrent Chunk Management Engine (Fabric)
Connectible Chains [Fabric]
Continuity
Controlling
Convenient mobGriefing
Create Fabric
Create Utilities
Create: Extended Cogwheels
Create: Steam 'n' Rails
Dark Waters
Debugify
Deeper Dark
Deeper and Darker
Despawning Eggs Hatch
DimensionalDoors
Drip Sounds (Fabric)
Droplight
Dungeons and Taverns
EMI
EMI Addon: Extra Mod Integrations
EMI Loot
EMI Trades
EMICompat
EMIffect
EdenRing
Enchantment Descriptions
Entity Collision FPS Fix
Entity Culling
Equipment Compare
Excorrelation
Explorer's Compass
Explorify
Explosive Enhancement
Fabric API
Fabric Language Kotlin
Falling Leaves
Fast Backups
Fast Leaf Decay
FerriteCore
Florcraft
Forge Config API Port
Fusion (Connected Textures)
Geckolib
Gigeresque
Haema
Handcrafted
Harvest with ease
Hybrid Aquatic
Iceberg
Immersive Armors
Indium
Infinity Buttons
Inventory Tabs (updated)
Iris Flywheel Compat
Iris Shaders
LambDynamicLights
LazyDFU
Legendary Tooltips
Let Me Despawn
Liberty's Villagers
Lithium
MVS - Moog's Voyager Structures
Marium's Soulslike Weaponry
Memory Leak Fix
MidnightLib
Mine Cells - Dead Cells Mod
Mob Plaques
Mod Menu
ModernFix
Moonlight Lib
More Doors
Mouse Tweaks
Nature's Compass
Neruina - Ticking Entity Fixer
No Chat Reports
Nyctophobia
Nyctophobia Dread
Nyf's Spiders
Patchouli
Phosphor
Prism
Puzzles Lib
Reaper
Rechiseled
Rechiseled: Create
Regions Unexplored
Resourceful Lib
Revelationary
Sculk Expansion
Simply Swords
SmartBrainLib
Sodium
Sound Physics Remastered
Special Mobs
Spectrum
Spirit
SuperMartijn642's Config Lib
SuperMartijn642's Core Lib
TerraBlender
TerraMine
The Graveyard (FABRIC)
Tool Stats
ToolTipFix
Tree Harvester
Trinkets
Ultris: Boss Expansion
Upgraded Mobs
Visual Overhaul
Visuality
Vitalize
WTHIT
Wormhole (Portals)
Xaero's Minimap
Xaero's World Map
YUNG's API
YUNG's Better Ocean Monuments
YetAnotherConfigLib
You're in Grave Danger
Yttr
Zoomify
bad packets
megane
oωo (owo-lib)
playerAnimator

**Comment by mim1q** [comment]
Can you check if it still happens without Concurrent Chunk Management Engine?

**Comment by Zarvera** [comment]
Yes! Disabling CCME actually made instance unable to launch at all, for some reason due to other mod which i have on the suspect list for messing up entire instance, Haema. 
Disabling both resolved this issue, MineCells dimension now loads perfectly fine.
Thank you very much, mim1q!

**Comment by k1r1enko** [comment]
I have the same problem without CCME. Should I also give you a mod list to check where is problem?
 Minecells 1.6.2 version

**Comment by mim1q** [comment]
> I have the same problem without CCME. Should I also give you a mod list to check where is problem? Minecells 1.6.2 version

Could also be Sparser Structures. You can try removing it or blacklisting Mine Cells in the config. If it's not that, send the modlist, I'll see if there's anything suspicious

**Comment by k1r1enko** [comment]
Here it is: https://pastebin.com/nByPBjvW

**Comment by mim1q** [comment]
You do have Sparse Structures, that is probably the culprit
