### ISSUE TITLE
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'minecells'!

### ISSUE THREAD

**Issue by 8Asto8** [mim1q/MineCells#65]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'minecells'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/object/builder/v1/block/type/WoodTypeBuilder
	at com.github.mim1q.minecells.registry.featureset.WoodSet.<init>(WoodSet.java:19) ~[minecells-1.5.7.jar:?]
	at com.github.mim1q.minecells.registry.MineCellsBlocks.<clinit>(MineCellsBlocks.java:31) ~[minecells-1.5.7.jar:?]
	at com.github.mim1q.minecells.MineCells.onInitialize(MineCells.java:42) ~[minecells-1.5.7.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.object.builder.v1.block.type.WoodTypeBuilder
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at com.github.mim1q.minecells.registry.featureset.WoodSet.<init>(WoodSet.java:19) ~[minecells-1.5.7.jar:?]
	at com.github.mim1q.minecells.registry.MineCellsBlocks.<clinit>(MineCellsBlocks.java:31) ~[minecells-1.5.7.jar:?]
	at com.github.mim1q.minecells.MineCells.onInitialize(MineCells.java:42) ~[minecells-1.5.7.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
	... 6 more

[main/INFO]: Loading 167 mods:
	- amarite 1.0.8
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.9
	   \-- reach-entity-attributes 2.4.0
	- appleskin 2.5.1+mc1.20
	- architectury 9.1.12
	- autoslabs 1.1.3
	   |-- advanced_runtime_resource_pack 0.8.0
	   \-- statement 4.2.8+1.14.4-1.20.1
	        |-- kanos_config 0.4.1+1.14.4-1.19.4
	        \-- statement_vanilla_compatibility 1.0.1+1.16.5-1.17
	- badpackets 0.4.3
	- balm-fabric 7.1.4
	- bclib 3.0.13
	   \-- wunderlib 1.1.5
	- bettercombat 1.8.2+1.20.1
	- betterdeserttemples 1.20-Fabric-3.0.3
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.20-Fabric-4.0.3
	- betterend 4.0.10
	- betterendisland 1.20-Fabric-2.0.4
	- betterfortresses 1.20-Fabric-2.0.5
	- betterjungletemples 1.20-Fabric-2.0.4
	- bettermineshafts 1.20-Fabric-4.0.4
	- betternether 9.0.9
	- betteroceanmonuments 1.20-Fabric-3.0.3
	- betterstrongholds 1.20-Fabric-4.0.3
	- bettervillage 3.1.0
	- betterwitchhuts 1.20-Fabric-3.0.3
	- bosses_of_mass_destruction 1.7.2-1.20
	   |-- maelstrom_library 1.6-1.20
	   \-- multipart_entities 1.5-1.20
	- cardinal-components 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- chunky 1.3.92
	- cloth-config 11.1.106
	   \-- cloth-basic-math 0.6.1
	- collective 6.57
	- debugify 1.20+1.1
	- diagonalfences 7.0.0
	- doubledoors 4.5
	- elytra_aeronautics 1.3.0
	   \-- com_google_code_gson_gson 2.10.1
	- fabric-api 0.83.0+1.20
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c927
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b27
	   |-- fabric-block-api-v1 1.0.9+e022e5d127
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b27
	   |-- fabric-client-tags-api-v1 1.0.20+b3afc78b27
	   |-- fabric-command-api-v1 1.2.32+f71b366f27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-commands-v0 0.2.49+df3654b327
	   |-- fabric-containers-v0 0.1.61+df3654b327
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b27
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b27
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe27
	   |-- fabric-data-generation-api-v1 12.1.10+b3afc78b27
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b27
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b27
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b27
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b327
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a27
	   |-- fabric-item-api-v1 2.1.26+b3afc78b27
	   |-- fabric-item-group-api-v1 4.0.7+b3afc78b27
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da27
	   |-- fabric-keybindings-v0 0.2.34+df3654b327
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-loot-api-v2 1.1.37+b3afc78b27
	   |-- fabric-loot-tables-v1 1.1.41+9e7660c627
	   |-- fabric-message-api-v1 5.1.6+b3afc78b27
	   |-- fabric-mining-level-api-v1 2.1.47+b3afc78b27
	   |-- fabric-models-v0 0.3.35+b3afc78b27
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b27
	   |-- fabric-networking-v0 0.3.48+df3654b327
	   |-- fabric-object-builder-api-v1 11.0.6+b3afc78b27
	   |-- fabric-particles-v1 1.0.28+b3afc78b27
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b27
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b27
	   |-- fabric-renderer-api-v1 3.0.1+b3afc78b27
	   |-- fabric-renderer-indigo 1.3.1+b3afc78b27
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b327
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b27
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b27
	   |-- fabric-rendering-v0 1.1.47+df3654b327
	   |-- fabric-rendering-v1 3.0.6+b3afc78b27
	   |-- fabric-resource-conditions-api-v1 2.3.4+b3afc78b27
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b27
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b27
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b27
	   |-- fabric-transfer-api-v1 3.2.2+b3afc78b27
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b27
	- fabric-language-kotlin 1.10.13+kotlin.1.9.20
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.20
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.22.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.0
	- fabricloader 0.14.24
	- fastload 3.4.0
	   |-- conditional-mixin 0.3.2
	   |-- fastload-119-0-1-2-compat 3.4.0
	   |-- fastload-1193-compat 3.4.0
	   |-- fastload-1194-compat 3.4.0
	   \-- fastload_fapi_forward 1.0.2
	- ferritecore 6.0.1
	- forgeconfigapiport 7.0.0
	- fwaystones 3.1.3+mc1.20
	- geckolib 4.2.2
	   \-- com_eliotlash_mclib_mclib 20
	- hopobetterruinedportal 1.3.7
	- icarus 1.16
	- illegal_stack_fixer 1.0.0
	- java 20
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lazydfu 0.1.3
	- legendary_origins 1.2310.3
	- leveltextfix 6.0.1
	- libraryferret 4.0.0
	- lithium 0.11.2
	- lootr 0.7.29.75
	- mcda 5.0.1
	- mcdar 3.0.0
	- mcde 1.5.3.1-1.20
	   |-- blue_endless_jankson 1.2.3
	   \-- com_hrakaroo_glob 0.9.0
	- mcdw 8.1.0
	- memoryleakfix 1.1.2
	- midnightlib 1.4.1
	- minecells 1.5.7
	   \-- omega-config 1.2.3-1.18.1
	- minecraft 1.20
	- modernfix 5.0.2+mc1.20
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-models-v0 0.3.35+b3afc78b27
	   \-- fabric-screen-api-v1 2.0.6+b3afc78b27
	- mr_amethyst_golem 1.0
	- mr_edf_remastered 4.3
	- mr_hostile_mobsimproveovertime 1.6
	- mr_sanguine 0.4.0
	- notenoughcrashes 4.4.4+1.20
	- origins 1.10.0
	   \-- apoli 2.9.0
	        |-- additionalentityattributes 1.3.0+1.20.0
	        |-- calio 1.11.0
	        \-- playerabilitylib 1.8.0
	- overenchanted 1.2.0
	- owo 0.11.0+1.20
	- paxi 1.20-Fabric-4.0
	- player-animator 1.0.2-rc1+1.20
	- puzzleslib 7.0.9
	- qu-enchantments 1.3.6-1.20
	   \-- mm 2.3
	- roughlyenoughitems 12.0.674
	   \-- error_notifier 1.0.9
	- simplyswords 1.51.5-1.20.1
	   \-- spruceui 5.0.0+1.20
	- starlight 1.1.2+fabric.dbc156f
	- taxfreelevels 1.3.6
	- tectonic 2.1.1
	- terralith 2.4.8
	- trinkets 3.7.1
	- villagernames 5.2
	- voicechat 1.20-2.4.9
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da27
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b27
	   \-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	- wthit 8.3.0
	- yungsapi 1.20-Fabric-4.0.2
	   \-- org_javassist_javassist 3.29.2-GA
	- yungsbridges 1.20-Fabric-4.0.3
	- yungsextras 1.20-Fabric-4.0.3
	
Server Fabric 1.20  
Fabric Loader 1.14.24
Minecells 1.5.7

**Comment by 8Asto8** [comment]
Help me please :(

When loading the server, it will crash.

**Comment by mim1q** [comment]
Hello, I think there's nothing I can do, unfortunately.
Mine Cells used to work with 1.20 for a bit of time, so I left the version marked as supported, but it seems that is no longer the case :(
I'm going to remove 1.20 from the version list in the future, and only keep 1.20.1. Sorry for not being able to maintain multiple versions of the mod, but my current life schedule barely allows me to work on the latest one 😭

**Comment by 8Asto8** [comment]
Thank you very much for the answer. I understand everything, it's sad of course that he is no longer compatible. Good luck to you, thank you for such a wonderful mod.
