### ISSUE TITLE
[EntityCulling Incompatibility] Elevator Movement Not Shown

### ISSUE THREAD

**Issue by JLUsr** [mim1q/MineCells#7]
If the Elevator is not within the view of the camera then it won't render its movement when called. The block entity itself will still make its way down and damage players or obstruct their movement; however, it is treated like a ghost block.

https://user-images.githubusercontent.com/47650360/191851128-b0af9c17-6c62-4c82-a36e-4a421d8c13ff.mp4

Just wanted to include how much I absolutely love these elevators. Honestly, it's to the point where I wish you had a standalone for it so I could use them all the time. 10/10 mod as a whole.

**Comment by mim1q** [comment]
Hey, thanks for reporting!
Is this on a server or in singleplayer?

**Comment by mim1q** [comment]
I could not replicate this issue myself, however I did think of a possible solution in d70704df21f5d284a86f2b62772e068ef09ea282.
Is it okay if I leave this issue open and ping you once the next version comes out to verify whether it worked?
