### ISSUE TITLE
Minecells 1.5.3 Random CTD's in promenade, caused by Protector and/or Disgusting Worm

### ISSUE THREAD

**Issue by SylisMC** [mim1q/MineCells#73]
### **Description:**
I get crashes randomly in the promenade dimension, it doesn't happen in creative.

[latest.log](https://github.com/mim1q/MineCells/files/13625683/latest.log)
[crash-2023-12-09_16.19.19-server.txt](https://github.com/mim1q/MineCells/files/13625684/crash-2023-12-09_16.19.19-server.txt)

The same crash occers when spawning either of these two entities via command or spawnegg

Spawning Disgusting Worm
[latest.log](https://github.com/mim1q/MineCells/files/13625648/latest.log)
[crash-2023-12-09_16.02.11-server.txt](https://github.com/mim1q/MineCells/files/13625649/crash-2023-12-09_16.02.11-server.txt)

Spawning Protector
[latest.log](https://github.com/mim1q/MineCells/files/13625659/latest.log)
[crash-2023-12-09_16.05.40-server.txt](https://github.com/mim1q/MineCells/files/13625657/crash-2023-12-09_16.05.40-server.txt)

### **Mod List:**
Roughly Enough Items (REI) - 9.1.668+fabric
Architectury API - 6.5.85+fabric
Cloth Config API - 8.3.103+fabric
Fabric API - 0.77.0+1.19.2
Mine Cells - Dead Cells Mod - 1.5.3
oωo (owo-lib) - 0.9.3+1.19

**Comment by mim1q** [comment]
As said on the Discord - temporary solution is to downgrade Fabric Loader to 0.14.x.
Will be fixed in the next release(s)!

**Comment by mim1q** [comment]
Fixed in latest versions for both 1.19.2 and 1.20.1. Alternatively downgrading Fabric Loader works for older versions
