### ISSUE TITLE
Lags when flying aroud in promenade

### ISSUE THREAD

**Issue by Rad586** [mim1q/MineCells#79]
![image](https://github.com/mim1q/MineCells/assets/99306685/ee4a0908-dd36-4eab-a108-5ab43a4d2f14)
![image](https://github.com/mim1q/MineCells/assets/99306685/5466b0d6-b175-45a5-bba7-2004a79a94ea)
**Minecraft 1.19.2, Minecells 1.5.8.** ONLY MINECELLS AND ITS DEPENDENCIES INSTALLED. 
When stop moving, lags are gone. 
It was tested in peaceful mode, so maybe it's not a problem on spawn runes. 

Edit: 
When I changed view distance to 4, the lag still exists. 
![image](https://github.com/mim1q/MineCells/assets/99306685/e6ea94fc-4054-4ffd-8184-25282ac40d68)

**Comment by mim1q** [comment]
This is most likely the tree generation code, actually (namely the leaves). I've been trying to find a better way to generate those without causing so much lag but so far I haven't been successful 😅

**Comment by Rad586** [comment]
What about make it generate as structure(instead of feature), and use expansion hack(for top)? 
I've seen towers of the wild datapack doing this for tower top variants, not sure if it helps reducing the lag. 

Also, those leaves are somehow decaying, with fast leave decay mod and auto plant mod, it becames extremely laggy. I ran `kill @e[type=item]` command and cleared 5000+ items...

**Comment by Rad586** [comment]
What about make it generate as structure(instead of feature), and use expansion hack(for top)? 
I've seen towers of the wild datapack doing this for tower top variants, not sure if it helps reducing the lag. 
Also, those leaves are somehow decaying, with fast leave decay mod and auto plant mod, it becames extremely laggy. I ran `kill @e[type=item]` command and cleared 5000+ items...

**Comment by mim1q** [comment]
I'm going to release an update soon that should hopefully fix this, at least partially 👍 
I optimized the leaf generation code massively, which is what caused the lag spikes in my case
