### ISSUE TITLE
Crash when trying to exit portal to overworld

### ISSUE THREAD

**Issue by LunexLunertic** [mim1q/MineCells#8]
This crash happens when I stand on the portal that leads to the overworld when I try to exit the dimension. This was during singleplayer. Do note that I am using Quilt's Fabric loader but nonetheless I will post this issue just in case anyone else runs into this problem since it mentions something about Ticking block entity.

[crash-2022-10-24_19.47.47-server.txt](https://github.com/mim1q/MineCells/files/9856785/crash-2022-10-24_19.47.47-server.txt)

Here's a video showing a demonstration of the crash in action, keep in mind that when it goes to a black screen that's the crash happening since I have the window only focused on the game in my OBS recorder.

https://youtu.be/aDmHOkFlfs4

**Comment by mim1q** [comment]
Hey, thanks for reporting!
Can you confirm whether the crash happens in every world or just this one?
Also - do any of the mods you have replace the overworld dimension

**Comment by mim1q** [comment]
Introduced a fallback in 1c5ff611fd68b41f81fdb61bece4b98b725c809d + fe7b93e418d320b465a28cef42cc9261743018c5
When the portal can't find the correct world data, it will teleport you to the last activated portal. If that fails, it will teleport you to the world spawn.
It's not the perfect solution, but it shouldn't crash!

**Comment by LunexLunertic** [comment]
I know I don't have any sort of mod that replaces the overworld dimension. Haven't seen if it happens in other worlds yet, but thanks for the update I will test it out now to see if it is actually fixed or not.

**Comment by mim1q** [comment]
@LunexLunertic, the new version (1.2.0) is now available on [Modrinth](https://modrinth.com/mod/minecells) and [CurseForge ](https://www.curseforge.com/minecraft/mc-mods/minecells).

**Comment by mim1q** [comment]
Should no longer happen. Closing. I'll reopen it if the issue comes up again
