### ISSUE TITLE
Flee goal for undead archers

### ISSUE THREAD

**Issue by Rad586** [mim1q/MineCells#84]
In deadcells, undead archers would step back if player gets close, but in minecells, they just stare at player, and pull the bow. 
It would be more interesting(and challenging) if they try to keep distance from player.

**Comment by mim1q** [comment]
That's the plan for one of the next updates, to add some jump back / run back goal to Undead Archers, Grenadiers, and Sweepers. I'll keep this issue up until I implement it to serve as a reminder 😁

**Comment by mim1q** [comment]
Added a jump back behavior for Grenadiers and Archers, and a roll back one for Sweepers!
