### ISSUE TITLE
[1.19.2] Crashes entering prison dimension from the end

### ISSUE THREAD

**Issue by Rad586** [mim1q/MineCells#88]
https://gist.github.com/Rad586/eb6f3981ffbcb49cbb4856a62b9ce6ed
I made "overworld portal" to spawn on end midlands, since minecells dimensions are hard. After entering the portal(in survival), the game crashes.

**Comment by mim1q** [comment]
The overworld is supposed to be the entrypoint for Mine Cells. I'm not planning to support the End and other dimensions as the entrypoints, as I can think of a few ways it could complicate the progression logic.
