### ISSUE TITLE
[1.19.2] C2ME breaks prison doorway

### ISSUE THREAD

**Issue by Rad586** [mim1q/MineCells#89]
When used with [C2ME](https://modrinth.com/mod/c2me-fabric), the doorway teleports player to the coordinates corresponding to where he enter the portal, instead of the prison structure. 
**Steps to reproduce:** 
1. Put down prison doorway and enter in **survival mode.** 

I tried disabling all options in C2ME, but the bug still exists.

**Comment by mim1q** [comment]
Possibly fixed in the latest release, there's a config option related to C2ME. Try and see if it works out of the box now, and if it doesn't, switch that new option off :thinking:

**Comment by Rad586** [comment]
Seems fixed in 1.20.1!
