### ISSUE TITLE
BOSS BUGGED

### ISSUE THREAD

**Issue by kayjguts** [mim1q/MineCells#91]
When the boss enters its invincible state and attacks with its tentacles it sometimes stops. Ive rejoined multiple times and the boss is still stuck with half hp. I cannot leave the room either. I cannot kill him either since its happening while he is invincible.

**Comment by kayjguts** [comment]
To clarify: I know he stays in that state until you kill all his tentacles but he isnt sending them out anymore and is stuck in that state.

**Comment by kayjguts** [comment]
Happening in minecraft 1.20.1

**Comment by kayjguts** [comment]
Lol this is genuinely irritating because I cant play the game

**Comment by mim1q** [comment]
Does this happen in the latest Mine Cells release? The tentacles should die out after around 3 minutes of spawning. I'll investigate is there's some issue preventing that

**Comment by mim1q** [comment]
If you want to just leave the room there's a config option that lets the entry door open even if the boss is still alive: `unlockedBossEntry`

**Comment by kayjguts** [comment]
> Does this happen in the latest Mine Cells release? The tentacles should die out after around 3 minutes of spawning. I'll investigate is there's some issue preventing that

I see now that the mine cells isnt the updated version, id have to contact the person who made the mod pack since its private

Thank you for quick response <3

**Comment by mim1q** [comment]
Likely fixed in the mentioned update, then. Closing!
