### ISSUE TITLE
проблема с боссом он не появляется как и другие данжи 

### ISSUE THREAD

**Issue by k1mpes** [mim1q/MineCells#94]
I enter the first dungeon, everything is fine, there is no boss of this dungeon. I thought ok, maybe I installed the mod crookedly, but no, I see that others are fine, but I’m not, I go into the second dungeon, and there’s also no fortress and boss there.

**Comment by mim1q** [comment]
Please only write issues in English. I won't be reviewing this once since after a quick google translate it doesn't seem to ask any particular question or report any issue
