### ISSUE TITLE
problem with dungeons and bosses

### ISSUE THREAD

**Issue by k1mpes** [mim1q/MineCells#95]
standard teleporters all work from time to time constant bugs teleport me instead of a location to the bowels of the earth, one boss doesn’t even have a revival rune, in the forest at spawn there is no tower for a new boss, even in the location itself there are new dungeons, but in the reviews for this mod . (maybe this is because it’s for the version, but there are no more than 2 dungeons, it’s a prison and a forest and that’s it!) Version 1.19.2 that I’m playing turns on and errors occur

**Comment by mim1q** [comment]
Thanks, I can work with this now😁 
The second boss and the Ramparts are only in the newest 1.20.1 versions of the mod, so I can't help you with that one.
Before that, there were actually 3 biomes: The Prisoners' Quarters, then the Promenade, where you have to find a Vine Rune, and after that, back in the Prison you can access the first and only boss.

There's a progression guide for this older version on the bottom of [this page](https://mim1q.dev/minecells/progression-guide/#progression-guide)

As for the teleporting errors: if you updated Mine Cells at any point, you should reset the dimensions so they can regenerate correctly, [like here](https://mim1q.dev/minecells/updating/). It might also be a mod like C2ME causing weirdness, so you might try to remove that if you have it and check it out again
