### ISSUE TITLE
Portal

### ISSUE THREAD

**Issue by Minecrafterthebuilder** [mim1q/MineCells#97]
my portal has bars over it for some reason and i cant walk through it but my friends can

**Comment by mim1q** [comment]
What dimension does the Doorway lead to? Make sure you visit that dimension the "normal" way before using a doorway as a shortcut - only then will the portal open up for you. I can't make it teleport you directly to the dimension without that, or the progression might get screwed up. I'll try to figure out a config option in the future to allow that, tho

**Comment by Minecrafterthebuilder** [comment]
I fixed my issue. For some reason it turned my portal into the promenade.
