### ISSUE TITLE
java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.attack_damage

### ISSUE THREAD

**Issue by JellyBubb1e** [mim1q/MineCells#99]
[crash-2024-03-03_20.36.50-server.txt](https://github.com/mim1q/MineCells/files/14473001/crash-2024-03-03_20.36.50-server.txt)
 Perhaps related to my use of modifying weapon attributes with [CIA](https://github.com/nvb-uy/cia).
MC Version: 1.20.1
MineCells Mod version: 1.7.1
Fabric Loader: 0.15.7

**Comment by mim1q** [comment]
Any context on when this happens? Is it when you get hit with the projectile?

**Comment by JellyBubb1e** [comment]
https://github.com/mim1q/MineCells/assets/107482912/c522b443-2c7a-496b-9298-fbbbab26e96c

It seems so.😢

**Comment by JellyBubb1e** [comment]
hmm...my bad.This is an issue caused by the Aylyth mod.

**Comment by mim1q** [comment]
I see. Let me know if it reappears and I'll see if I can prevent it on my side :grin:
